<a href="https://colab.research.google.com/github/vin-99/ASS4/blob/main/Numpy_ass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


arr = np.zeros(10,dtype = int)
arr[4] = 1

print(arr)

[0 0 0 0 1 0 0 0 0 0]


In [2]:
array_1 = np.arange(10,50)

array_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
array_2 = np.arange(0,9).reshape(3,3)

print(array_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
n_array = np.array([1,2,0,0,4,0])

print("Original array:")
print(n_array)

# np.nonzero()
print("\nIndices of null elements:")

res = np.nonzero(n_array == 0)
print(res)

Original array:
[1 2 0 0 4 0]

Indices of null elements:
(array([2, 3, 5]),)


In [6]:
import numpy as np

n_array = np.random.random((10,10))

print("the original array",n_array)

print("\n\n")
print("the minimum value of n_array: \n",n_array.min())
      
print("\n\n")
print("the maximun value of n_array: \n",n_array.max())

the original array [[0.2575441  0.62073504 0.61274089 0.54255803 0.98706439 0.10620198
  0.02980007 0.10652165 0.35143346 0.0793898 ]
 [0.52243434 0.52486024 0.00276732 0.83674435 0.94209564 0.94254971
  0.12378702 0.54043856 0.590918   0.17456011]
 [0.71028152 0.87725762 0.40704061 0.58301003 0.85347851 0.43554272
  0.63172246 0.02442502 0.94291718 0.19331374]
 [0.38883115 0.27404324 0.44077649 0.2331764  0.84085127 0.74099439
  0.37275264 0.52437037 0.36140332 0.88525743]
 [0.36425518 0.40234144 0.8501035  0.93078242 0.25624662 0.05034072
  0.42043216 0.19423422 0.99586142 0.30365257]
 [0.7861815  0.33727423 0.34726249 0.92369409 0.24207914 0.42032254
  0.81402471 0.96770181 0.39294735 0.42036843]
 [0.61169506 0.05505063 0.31559364 0.4781031  0.72473294 0.06358725
  0.58845402 0.65168008 0.18945945 0.29295448]
 [0.43850407 0.55657916 0.99477277 0.11196111 0.74664999 0.43643858
  0.62970764 0.01803626 0.21225248 0.20281051]
 [0.34618356 0.55255352 0.4176382  0.9778697  0.06447466 0.27

In [10]:
import numpy as np

z = np.random.random(30)
print("the random array is: \n",z)

mean_1 = z.mean()
print("\n\nthe mean value of array: \n ",mean_1)

the random array is: 
 [0.44153565 0.38835545 0.67609432 0.96624653 0.7823179  0.52525333
 0.94106207 0.64541941 0.15310984 0.46496309 0.74653972 0.88230047
 0.03974551 0.94736276 0.89412461 0.30725423 0.5874013  0.03432226
 0.46682439 0.7820932  0.54611331 0.94452052 0.61607929 0.16460214
 0.06797452 0.26112576 0.62034509 0.57268133 0.10222066 0.77112835]


the mean value of array: 
  0.5446372341504714
